// Code generated by github.com/BitRainforest/filmeta-gen from github.com/BitRainforest/bony/lens DO NOT EDIT.
export const ServiceMethods = {
  "AuthBonyVerify": {},
  "BlockHeaderByCid": {},
  "BlockMessageCidsByCid": {},
  "BlockMessagesByCid": {},
  "BlockRewardByCid": {},
  "InternalMessageBySourceMessage": {},
  "MessageByCid": {},
  "MinerBurnAmount": {},
  "MinerSectorEventCount": {}
}