// Code generated by github.com/BitRainforest/filmeta-gen from github.com/BitRainforest/bony/lens DO NOT EDIT.
export declare const ChainMethods: {
  "ChainGetBlock": {};
  "ChainGetBlockMessages": {};
  "ChainGetGenesis": {};
  "ChainGetParentMessages": {};
  "ChainGetParentReceipts": {};
  "ChainGetTipSet": {};
  "ChainGetTipSetAfterHeight": {};
  "ChainGetTipSetByHeight": {};
  "ChainHasObj": {};
  "ChainHead": {};
  "ChainNotify": {
    "subscription": boolean;
  };
  "ChainReadObj": {};
  "ChainSetHead": {};
  "ChainStatObj": {};
};
export declare const StateMethods: {
  "StateChangedActors": {};
  "StateGetActor": {};
  "StateGetReceipt": {};
  "StateListActors": {};
  "StateMarketDeals": {};
  "StateMinerDeadlines": {};
  "StateMinerInfo": {};
  "StateMinerPartitions": {};
  "StateMinerPower": {};
  "StateMinerSectorAllocated": {};
  "StateMinerSectorCount": {};
  "StateNetworkName": {};
  "StateReadState": {};
  "StateSectorExpiration": {};
  "StateSectorGetInfo": {};
  "StateSectorPartition": {};
  "StateSectorPreCommitInfo": {};
  "StateVMCirculatingSupplyInternal": {};
};
export declare const ModelServiceMethods: {
  "BlockHeaderByCid": {};
  "BlockMessageCidsByCid": {};
  "BlockMessagesByCid": {};
  "BlockRewardByCid": {};
  "InternalMessageBySourceMessage": {};
  "MessageByCid": {};
  "MinerBurnAmount": {};
  "MinerSectorEventCount": {};
};
